// Decompiled with JetBrains decompiler
// Type: Game.Prefabs.NetPieceRequirements
// Assembly: Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 9DBFD0F8-0F1C-47CD-A752-F580C9797E08
// Assembly location: G:\SteamLibrary\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Game.dll

#nullable disable
namespace Game.Prefabs
{
  public enum NetPieceRequirements
  {
    Node,
    Intersection,
    DeadEnd,
    Crosswalk,
    BusStop,
    Median,
    TrainStop,
    OppositeTrainStop,
    Inverted,
    TaxiStand,
    LevelCrossing,
    Elevated,
    Tunnel,
    Raised,
    Lowered,
    LowTransition,
    HighTransition,
    WideMedian,
    TramTrack,
    TramStop,
    OppositeTramTrack,
    OppositeTramStop,
    MedianBreak,
    ShipStop,
    Sidewalk,
    Edge,
    SubwayStop,
    OppositeSubwayStop,
    MiddlePlatform,
    Underground,
    Roundabout,
    OppositeSidewalk,
    SoundBarrier,
    Overhead,
    TrafficLights,
    PublicTransportLane,
    OppositePublicTransportLane,
    Spillway,
    MiddleGrass,
    MiddleTrees,
    WideSidewalk,
    SideGrass,
    SideTrees,
    OppositeGrass,
    OppositeTrees,
    Opening,
    Front,
    Back,
    Flipped,
    RemoveTrafficLights,
    AllWayStop,
    Pavement,
    Gravel,
    Tiles,
    ForbidLeftTurn,
    ForbidRightTurn,
    OppositeWideSidewalk,
    OppositeForbidLeftTurn,
    OppositeForbidRightTurn,
    OppositeSoundBarrier,
    SidePlatform,
    AddCrosswalk,
    RemoveCrosswalk,
    Lighting,
    OppositeBusStop,
    OppositeTaxiStand,
    OppositeRaised,
    OppositeLowered,
    OppositeLowTransition,
    OppositeHighTransition,
    OppositeShipStop,
    OppositePlatform,
    OppositeAddCrosswalk,
    OppositeRemoveCrosswalk,
    Inside,
    ForbidStraight,
    OppositeForbidStraight,
    Hidden,
  }
}
